function facebookshare_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/facebookshare':
    case 'admin/help#facebookshare':
      return '<p>'. t('<a href="@facebookshare">facebookshare</a> provides a way of tracking popular links on <a href="@facebookshare">Facebook</a>.', array('@facebookshare' => 'http://facebook.com', '@facebookshare' => 'http://facebook.com')) .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function facebookshare_perm() {
  return array(
    'administer facebookshare',
    'access facebookshare',
  );
}

/**
 * Implementation of hook_menu().
 */
function facebookshare_menu() {
  $items['admin/settings/facebookshare'] = array(
    'title' => 'facebookshare',
    'description' => 'Provides the configuration options for how facebookshare operates on the site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('facebookshare_admin_settings'),
    'access arguments' => array('administer facebookshare'),
    'file' => 'facebookshare.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_nodeapi().
 */
function facebookshare_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if ($op == 'view') {
    // Make sure we're on the right content type.
    if (!in_array($node->type, variable_get('facebookshare_types', array()), TRUE)) {
      return NULL;
    }

    // Make sure we're actually building the page to render in a browser.
    if ($node->build_mode != NODE_BUILD_NORMAL) {
      return NULL;
    }

    // Make sure the user has access to use TweetMeme.
    if (!user_access('access facebookshare')) {
      return NULL;
    }

    // Retrieve the location where we should show it, the style and the URL of the button.
    $location = variable_get('facebookshare_location', array());
    $style = variable_get('facebookshare_style', 'normal');
    $url = url('node/' . $node->nid, array('absolute' => TRUE));

    // Check in the teaser view.
    if ($teaser && !empty($location['teasers'])) {
      $node->content['facebookshare'] = array(
        '#value' => theme('facebookshare_button', $url, $style),
        '#weight' => -10,
      );
    }
    // Check in the full view.
    else if(!$teaser && !empty($location['content'])) {
      $node->content['facebookshare'] = array(
        '#value' => theme('facebookshare_button', $url, $style),
        '#weight' => -10,
      );
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function facebookshare_theme($existing, $type, $theme, $path) {
  return array(
    'facebookshare_button' => array(
      'arguments' => array(
        'url' => NULL,
        'style' => NULL,
      ),
    ),
  );
}

/**
 * Displays the facebookshare button
 */
function theme_facebookshare_button($url, $style = 'normal') {
  drupal_add_css(drupal_get_path('module', 'facebookshare') . '/facebookshare.css');
  $output = '<div class="facebookshare facebookshare-button"><a name="fb_share" type="';
  if ($style != 'normal') {
    $output .= "facebookshare_style = '$style';";
  }
  $output .= ' href="http://www.facebook.com/sharer.php">Share</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script></div>';
  return $output;
}